fixtures:
  repositories:
    "periodicnoise" : "https://github.com/Jimdo/puppet-periodicnoise.git"
    "puppetlabs-stdlib" : "https://github.com/puppetlabs/puppetlabs-stdlib.git"
  symlinks:
    "duplicity": "#{source_dir}"
